apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

commonLabels:
  app: boilerplate-web
  managed-by: argocd
  component: application

images:
  - name: ghcr.io/5iing/docker-sample-image/my-app
    newTag: latest
