apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - prometheus-config.yaml
  - prometheus-deployment.yaml
  - prometheus-service.yaml

commonLabels:
  app: prometheus
  component: monitoring
  managed-by: argocd

namespace: monitoring
