apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - grafana-config.yaml
  - grafana-deployment.yaml
  - grafana-service.yaml

commonLabels:
  app: grafana
  component: monitoring
  managed-by: argocd

namespace: monitoring
